language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install msgpack-python
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - python setup.py install
  - python tests/
